// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txiqsanfzgohobqoqrjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aXFzYW5memdvaG9icW9xcmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTQ1ODksImV4cCI6MjA2MzY5MDU4OX0.XO1XVdVIuxUEj06vjqHN1g05LNZkisJzQFH4VqIKwt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);